### ISSUE TITLE
Code Release & Related Questions

### ISSUE THREAD

**Issue by reynoldscem** [EnVision-Research/LucidDreamer#1]
Hi, Really great work.

I was wondering if your codebase was based on threestudio? Further, do you have an intended timescale for your release? And do you know which license you intend to use?

**Comment by AbnerVictor** [comment]
Hi, thank you for reaching out.

Our codebase is still in progress, and we plan to release it very soon. Meanwhile, our code is not based on threestudio at the moment. We will check that more carefully since you ask.

For your information, we will probably use the MIT license.

**Comment by reynoldscem** [comment]
Thank you for the prompt reply and answers! Best of luck with your work!
