### ISSUE TITLE
Supplementary Material Issue

### ISSUE THREAD

**Issue by studying910** [EnVision-Research/LucidDreamer#13]
Thanks for the great work!

In the main text, it is mentioned that details are provided in the supplementary material. However, it can not be found in the Arxiv version. 

Could you please update it to add the supplementary material? Thx :)

**Comment by YixunLiang** [comment]
Hi,

Thanks for reaching out. We will do it ASAP.

**Comment by AbnerVictor** [comment]
Hi, we have updated our arxiv paper with the supplement attached, please kindy check

**Comment by tuning12** [comment]
Hi, I couldn't find the supplementary matrial in your latest arxiv version. Could you please share the link or something?

**Comment by tuning12** [comment]
> Hi, we have updated our arxiv paper with the supplement attached, please kindy check

Hi, I couldn't find the supplementary matrial in your latest arxiv version. Could you please share the link?

**Comment by AbnerVictor** [comment]
> > Hi, we have updated our arxiv paper with the supplement attached, please kindy check
> 
> Hi, I couldn't find the supplementary matrial in your latest arxiv version. Could you please share the link?

Please refer to this link for our paper [Arxiv_paper](https://arxiv.org/abs/2311.11284), the supplement starts from section. 7 of the paper (located on page 9)
