### ISSUE TITLE
Method Issue

### ISSUE THREAD

**Issue by studying910** [EnVision-Research/LucidDreamer#15]
According to the multi-step DDIM sampling, it is mentioned in Section 3.2 that Eqn. (13) is derived from Eqn. (11).

However, it is quite confused since Eqn. (11) seems incorrect.

The DDIM sampling seems to be:

$\frac{\tilde{x}_s}{\sqrt{\overline{\alpha}_s}}=\frac{x_t}{\sqrt{\overline{\alpha}_t}}+(\gamma(s)-\gamma(t)) \epsilon(x_t; y, \phi)$.

Since $\overline{\alpha}_0=1$, it can derive Eqn. (13).

Also, the notation of the sampling latents $\tilde{x}_s \dots$ is missed.

**Comment by AbnerVictor** [comment]
Thank you for asking.
Noted that Eqn.11 denotes the DDIM denoising process of $x_t \rightarrow \tilde{x}_{t-\delta_T}$, as we denote $s=t-\delta_T$, in which case, $\tilde{x}_s = \frac{x_t - \sqrt{1-\bar\alpha_t} \epsilon _\phi(x_t, t, y)}{\sqrt{\bar\alpha_t}} + \sqrt{1-\bar\alpha_s} \epsilon _\phi(x_t, t, y)$, after some simple computation, it can be simplified to Eqn.11 in our paper.

I hope this may answer your questions.

**Comment by AbnerVictor** [comment]
Thank you for asking, your induction is correct.

our original intention of Eqn.11 is to express the ddim denoising process in a similar way of Eqn.9, which is the ddim inversion. We make a mistake in the writing, we will fix that ASAP.

**Comment by studying910** [comment]
Thx for your answer :)
