### ISSUE TITLE
Error when installing requirements

### ISSUE THREAD

**Issue by brentjohnston** [EnVision-Research/LucidDreamer#17]
I was doing the instructions and it installs everything but gives this error at the end:

_ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton_

Any ideas? Using Anaconda on windows 11. 4090 here.

**Comment by YixunLiang** [comment]
Hi,

Thanks for reaching out. Please try to remove this line in requirements.txt and use pip to install trion manually. Also,  I remember that triton would not affect the using of our implementation. Just for solve a warning. So you can also just skip it.




---- Replied Message ----
| From | ***@***.***> |
| Date | 12/04/2023 08:41 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [EnVision-Research/LucidDreamer] Error when installing requirements (Issue #17) |

I was doing the instruction and it installs everything but gives this error at the end:

ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton

Any ideas?

**Comment by YixunLiang** [comment]
It seems like your cuda version is too old. Maybe update it to cuda 11.2 would solve this problem.



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/04/2023 09:56 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [EnVision-Research/LucidDreamer] Error when installing requirements (Issue #17) |

Thanks that worked, though I have a new error now (cuda 10.2 is installed to the proper directory)

Building wheels for collected packages: diff-gaussian-rasterization
Building wheel for diff-gaussian-rasterization (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [14 lines of output]
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'
running bdist_wheel
C:\Users\PC\anaconda3\envs\LucidDreamer\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
warnings.warn(msg.format('we could not find ninja.'))
running build
running build_py
creating build
creating build\lib.win-amd64-cpython-39
creating build\lib.win-amd64-cpython-39\diff_gaussian_rasterization
copying diff_gaussian_rasterization_init_.py -> build\lib.win-amd64-cpython-39\diff_gaussian_rasterization
running build_ext
C:\Users\PC\anaconda3\envs\LucidDreamer\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
warnings.warn(f'Error checking compiler version for {compiler}: {error}')
error: [WinError 2] The system cannot find the file specified
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for diff-gaussian-rasterization
Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

**Comment by brentjohnston** [comment]
yes its brentjohnson221@outlook.com

**Comment by TangYucopper** [comment]
Hi, may I get a copy of your environment.yaml? Unfortunately I cannot run your code even though I follow your installation procedure completely. It consistently produces CUDA errors such as "numel: integer multiplication overflow" and "illegal memory access"

**Comment by TangYucopper** [comment]
> Sure, please give me your email. But it might be diff-gaussian-rasterization problem, not the environment.
> 
> For the problem of cuda error. you can check this: [graphdeco-inria/gaussian-splatting#41](https://github.com/graphdeco-inria/gaussian-splatting/issues/41) . It might be helpful. BTW, Is your GPU RTX4090?
> 
> My nvcc version is:
> 
> nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2020 NVIDIA Corporation Built on Mon_Oct_12_20:09:46_PDT_2020 Cuda compilation tools, release 11.1, V11.1.105 Build cuda_11.1.TC455_06.29190527_0
> 
> > Hi, may I get a copy of your environment.yaml? Unfortunately I cannot run your code even though I follow your installation procedure completely. It consistently produces CUDA errors such as "numel: integer multiplication overflow" and "illegal memory access" @YixunLiang . Thanks in advance!

Thanks. My GPU is RTX4090. Let me first check the issue page.

**Comment by SweetCone1** [comment]
I encountered the same problem, has it been solved? I also installed two dependencies when running 3D gauss splatting, but they installed without any issues.

**Comment by SweetCone1** [comment]
> 谢谢，虽然我现在有一个新错误（cuda 10.2 已安装到正确的目录），但它有效
> 
> 为收集的包构建轮子： diff-gaussian-rasterization 用于 diff-gaussian-rasterization 的构建轮子 (setup.py) ... 错误 错误：subprocess-exited-with-error
> 
> × python setup.py bdist_wheel 未成功运行。 │ exit code: 1 ╰─> [14行输出] 找不到CUDA运行时，使用CUDA_HOME='C:\Program Files\NVIDIA GPUComputing Toolkit\CUDA\v10.2' 运行bdist_wheel C:\Users\PC\ anaconda3\envs\LucidDreamer\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: 尝试使用 ninja 作为 BuildExtension 后端，但我们找不到 ninja.. 回到使用缓慢的 distutils 后端。 warnings.warn(msg.format('我们找不到忍者。')) 运行构建 运行 build_py 创建构建 创建 build\lib.win-amd64-cpython-39 创建 build\lib.win-amd64-cpython-39\diff_gaussian_rasterization 复制 diff_gaussian_rasterization_ _init_ _.py -> build\lib.win-amd64-cpython-39\diff_gaussian_rasterization 运行 build_ext C:\Users\PC\anaconda3\envs\LucidDreamer\lib\site-packages\torch\utils\cpp_extension.py： 359: UserWarning: 检查 cl 的编译器版本时出错: [WinError 2] 系统找不到指定的文件 warnings.warn(f'检查 {compiler} 的编译器版本时出错: {error}') 错误: [WinError 2] 系统找不到指定的文件 [输出结束]
> 
> 注意：此错误源自子进程，并且可能不是 pip 的问题。 错误：为 diff-gaussian-rasterization 构建轮子失败 为 diff-gaussian-rasterization 运行 setup.py clean 无法构建 diff-gaussian-rasterization 错误：无法为 diff-gaussian-rasterization 构建轮子，这是安装 pyproject 所必需的。基于 toml 的项目

I encountered the same problem, has it been solved? I also installed two dependencies when running 3D gauss splatting, but they installed without any issues.

**Comment by SweetCone1** [comment]
> Thanks that worked, though I have a new error now (cuda 10.2 is installed to the proper directory)
> 
> Building wheels for collected packages: diff-gaussian-rasterization Building wheel for diff-gaussian-rasterization (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [14 lines of output] No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2' running bdist_wheel C:\Users\PC\anaconda3\envs\LucidDreamer\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend. warnings.warn(msg.format('we could not find ninja.')) running build running build_py creating build creating build\lib.win-amd64-cpython-39 creating build\lib.win-amd64-cpython-39\diff_gaussian_rasterization copying diff_gaussian_rasterization__init__.py -> build\lib.win-amd64-cpython-39\diff_gaussian_rasterization running build_ext C:\Users\PC\anaconda3\envs\LucidDreamer\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified warnings.warn(f'Error checking compiler version for {compiler}: {error}') error: [WinError 2] The system cannot find the file specified [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for diff-gaussian-rasterization Running setup.py clean for diff-gaussian-rasterization Failed to build diff-gaussian-rasterization ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

I encountered the same problem, has it been solved? I also installed two dependencies when running 3D gauss splatting, but they installed without any issues.

**Comment by AbnerVictor** [comment]
> > Thanks that worked, though I have a new error now (cuda 10.2 is installed to the proper directory)
> > Building wheels for collected packages: diff-gaussian-rasterization Building wheel for diff-gaussian-rasterization (setup.py) ... error error: subprocess-exited-with-error
> > × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [14 lines of output] No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2' running bdist_wheel C:\Users\PC\anaconda3\envs\LucidDreamer\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend. warnings.warn(msg.format('we could not find ninja.')) running build running build_py creating build creating build\lib.win-amd64-cpython-39 creating build\lib.win-amd64-cpython-39\diff_gaussian_rasterization copying diff_gaussian_rasterization__init__.py -> build\lib.win-amd64-cpython-39\diff_gaussian_rasterization running build_ext C:\Users\PC\anaconda3\envs\LucidDreamer\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified warnings.warn(f'Error checking compiler version for {compiler}: {error}') error: [WinError 2] The system cannot find the file specified [end of output]
> > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for diff-gaussian-rasterization Running setup.py clean for diff-gaussian-rasterization Failed to build diff-gaussian-rasterization ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects
> 
> I encountered the same problem, has it been solved? I also installed two dependencies when running 3D gauss splatting, but they installed without any issues.

Hi, your error indicates that there might be some problem with ninja, you may install ninja first.
