### ISSUE TITLE
question about mesh export

### ISSUE THREAD

**Issue by Asianfleet** [EnVision-Research/LucidDreamer#19]
How can I get the 3d mesh after training?

**Comment by AbnerVictor** [comment]
Hi, our current method is built on 3D gaussian splatting, which doesn't hold mesh by default.

You can access to the trained 3DGS in 'LucidDreamer/output/your_project_name/point_cloud' folder

**Comment by Asianfleet** [comment]
> Hi, our current method is built on 3D gaussian splatting, which doesn't hold mesh by default.
> 
> You can access to the trained 3DGS in 'LucidDreamer/output/your_project_name/point_cloud' folder

Thanks! This project is awesome！
