### ISSUE TITLE
ModuleNotFoundError: No module named 'point_e'

### ISSUE THREAD

**Issue by 838959823** [EnVision-Research/LucidDreamer#20]
After installing requirement.txt, I encountered this "ModuleNotFoundError: No module named 'point_e'". Where can I get this package? Thank you for your help.

**Comment by YixunLiang** [comment]
hi，

you can remove that line and install the pointe manually follow the instruction below:https://github.com/openai/point-e



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/13/2023 03:05 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [EnVision-Research/LucidDreamer] ModuleNotFoundError: No module named 'point_e' (Issue #20) |

After installing requirement.txt, I encountered this "ModuleNotFoundError: No module named 'point_e'". Where can I get this package? Thank you for your help.
