### ISSUE TITLE
The color of the generated characters is strange

### ISSUE THREAD

**Issue by MnKnight1** [EnVision-Research/LucidDreamer#21]
The color of the generated characters is yellow, is there any way to solve it? by setting text or parameters

https://github.com/EnVision-Research/LucidDreamer/assets/78358378/bd5c272b-a189-43cb-a354-61f0a0a414e1

https://github.com/EnVision-Research/LucidDreamer/assets/78358378/679c467f-243b-4781-b480-b79ae28c4063

**Comment by YixunLiang** [comment]
You can add some descriptions of weird colors to the negative prompt. It may work.

**Comment by MnKnight1** [comment]
Could you tell me the parameters in this github example?
![图片](https://github.com/EnVision-Research/LucidDreamer/assets/78358378/20d84877-661d-45b6-86da-a3ee23a01bd7)

**Comment by AbnerVictor** [comment]
> Could you tell me the parameters in this github example? ![图片](https://private-user-images.githubusercontent.com/78358378/291156897-20d84877-661d-45b6-86da-a3ee23a01bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzcyMjYsIm5iZiI6MTcwMjg3NjkyNiwicGF0aCI6Ii83ODM1ODM3OC8yOTExNTY4OTctMjBkODQ4NzctNjYxZC00NWI2LTg2ZGEtYTNlZTIzYTAxYmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA1MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYWZjNjBkMWUzYmNhYjYxYTVkNTdjOWY0YTIxOTExODRhMTA2ZDQ2NmVmNzA0OTFkZDhlNTI4MDlkM2VjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5z9XNLmWVbZYA0TWJAY5a5j30RNgR8VNit9-OyA_kD4)

Actually, we generate this figure with the majicMIX model from civitai. I guess that Einstein is difficult to generate because the diffusion model is incapable to provide high-quality supervision for Einstein. And you may try to increase the minimum delta_t to 80 or higher in your config to fix the color problem.

**Comment by MnKnight1** [comment]
Thanks,that's really helpful!
