### ISSUE TITLE
Comparison results of ISM with the multi-step DDIM baseline 

### ISSUE THREAD

**Issue by yxuhan** [EnVision-Research/LucidDreamer#23]
Hi, thanks for the awesome work and the code, it brings lots of valuable insights about the SDS to me!

From the paper I think the multi-step DDIM baseline can also solve the low feature consistency and low-quality problem of the vanila SDS loss; the proposed ISM is a spped-up version of this baseline method. What about the comparison results of the proposed ISM with this multi-step DDIM baseline in terms of running time and quality of the text-to-3D results?

**Comment by YixunLiang** [comment]
Hi, Thank you for recognizing our work!

Such comparisons are shown in supplement material. You could check Fig.10 and relative discussions.
