### ISSUE TITLE
How to finetune？

### ISSUE THREAD

**Issue by JAMESYJL** [EnVision-Research/LucidDreamer#27]
I want to load the trained LucidDreamer model and then proceed with further finetune, what should I do?

**Comment by YixunLiang** [comment]
Hi, sorry for the late reply, if you want to use other tech for finetuning, you can get the generated results in the “/output/” folder. If you want to further use our pipeline, you can add the path of generated results  to here to load the model:
   https://github.com/EnVision-Research/LucidDreamer/blob/fe499c0c2b1c070331ac54469eced2ad4aeda451/arguments/__init__.py#L117
