### ISSUE TITLE
Does LucidDreamer train a lora during iterations like ProlificDreamer?

### ISSUE THREAD

**Issue by MrForExample** [EnVision-Research/LucidDreamer#28]
You mentioned lora in the paper, so just asking it for clarify, since it almost take twice amount of time to run LucidDreamer  than to run [prolificdreamer](https://github.com/thu-ml/prolificdreamer)

**Comment by YixunLiang** [comment]
Hi, sorry for the late reply, we don't need to train a Lora during iterations.  For acceleration, you can try to modify the   '''xs_delta_t: 200''' and '''xs_inv_steps: 5''' in the original config to  '''xs_delta_t: 1000''' and '''xs_inv_steps: 1''', it means that you only use 1 step in ddim inversion. Our extra overhead should only exist with DDIM inversion compared with SDS.
