### ISSUE TITLE
Inquiry regarding method part

### ISSUE THREAD

**Issue by shim94kr** [EnVision-Research/LucidDreamer#29]
Thanks for sharing the code and presenting such a great paper!

I have a question about how the Equation 7 is derived from Equation 5 and how the gradient computation and the additional gamma term are included in the equation. Could you please provide some insights or explanations on this?

Thank you!

**Comment by AbnerVictor** [comment]
> Thanks for sharing the code and presenting such a great paper!
> 
> I have a question about how the Equation 7 is derived from Equation 5 and how the gradient computation and the additional gamma term are included in the equation. Could you please provide some insights or explanations on this?
> 
> Thank you!

Thank you for asking. In our paper, we quote Eqn. 5 and 6 from [the original SDS paper](https://dreamfusion3d.github.io). In Eqn. 7, we intent to present an equivalent transformation of the Eqn. 5 to ease our following explanation. Basically, it is a simple transformation which replace the subtraction of noises in the SDS loss with the subtraction of clean images.

There are some typos in Eqn. 7, where we wrongly introduce the derivatives notations, we will fix that ASAP.

**Comment by shim94kr** [comment]
Thank you for answering. I have one more question regarding equation 5-6. The original paper only introduce, as far as I know, the gradient of SDS loss not the exact form of SDS loss as equation 5. Does the original paper mention the exact form of SDS loss? and also, if you define SDS loss as (5) can equation (6) be derived based upon eq. (5)? I think this mismatches to the original paper. Thank you!
