### ISSUE TITLE
Question about algorithm

### ISSUE THREAD

**Issue by tuning12** [EnVision-Research/LucidDreamer#31]
Thank you for your great work! In algorithm 1, the noise added is fixed (determined by unet and x_0). However, in the "train_step_perpneg" function, a random noise is added which is different from the algorithm 1.

**Comment by YixunLiang** [comment]
Hi, thanks for your attention.

I just checked our code, and it seems like we don't have this bug, 
I think there is a misleading in : [         
prev_noisy_lat = self.scheduler.add_noise(latents, noise, self.timesteps[ind_prev_t]) ](https://github.com/EnVision-Research/LucidDreamer/blob/bbd8a6ad69f8d9d43fc76822a5910406223ed03a/guidance/sd_utils.py#L175C1-L175C98)
However, the ind_prev_t will always be set to 0 at each step. Apologize for it.

**Comment by tuning12** [comment]
Thank you for your patient reply!
