### ISSUE TITLE
About the visualization

### ISSUE THREAD

**Issue by gaost-Sun** [EnVision-Research/LucidDreamer#32]
Thanks for sharing this excellent work!
I woudl like to ask that how can I visualize the gaussian points and the in-time rendered results? Are there any relevant tutorials or README?

Looking forward your reply!

**Comment by AbnerVictor** [comment]
Our generated 3DGS is fully compatible with the original 3DGS repo: [link](https://github.com/graphdeco-inria/gaussian-splatting). You can follow their instructions, thanks for your interest.
