### ISSUE TITLE
About the reproduction of figs in the paper

### ISSUE THREAD

**Issue by chenxinl** [EnVision-Research/LucidDreamer#33]
Hi, 

Thanks for your great work.

I tried to reproduce the figs such as Fig. 1 in the paper following the training scripts in ./configs with some modifications. But the results are less than satisfactory.

Could you give more training configs of Fig. 1 in the paper? 

Thanks.

**Comment by AbnerVictor** [comment]
Hi, a similar issue has been answered in #22 , please feel free to ask if you have any further questions.
