### ISSUE TITLE
How to extract mesh/get normal?

### ISSUE THREAD

**Issue by kszpxxzmc** [EnVision-Research/LucidDreamer#34]
May I ask what is the data format for the final point_cloud_rgb.txt and point_cloud.ply and if it is possible to provide code for extracting mesh/obtaining normals？

**Comment by AbnerVictor** [comment]
Thank you for your interest.
In our project, we adopt 3D Gaussian Splatting (3DGS) as our major 3D representation, you can check more about [3DGS at this link](https://github.com/graphdeco-inria/gaussian-splatting).
Meanwhile, the 3DGS doesn't support mesh and normal extraction by default; there might be some recent works, such as SuGaR,  that support such features.

**Comment by kszpxxzmc** [comment]
Sorry, this is just a case of individual models. I will regenerate them
