### ISSUE TITLE
Gradio Demo

### ISSUE THREAD

**Issue by AK391** [EnVision-Research/LucidDreamer#5]
Hi congrats on LucidDreamer, would be great to setup a gradio demo for it on Hugging Face

In case you're interested, this is a [step-by-step guide](https://huggingface.co/docs/hub/spaces-sdks-gradio) explaining the process of creating a gradio sdk on Spaces. 😊 This is our docs on [Community GPU Grants](https://huggingface.co/docs/hub/spaces-gpus#community-gpu-grants). cc: @yvrjsharma

**Comment by AbnerVictor** [comment]
Thank you for asking! 
We also think it will be great to setup a demo. We will try to figure it out soon.

**Comment by haodong2000** [comment]
Thanks @AK391 ([@_akhaliq](https://twitter.com/_akhaliq))
 for sharing our work [#LucidDreamer](https://twitter.com/hashtag/LucidDreamer?src=hashtag_click)!

The live demo is released on 🤗
[@huggingface](https://twitter.com/huggingface)
: https://huggingface.co/spaces/haodongli/LucidDreamer, please check it out if interested. 

*Note that it is strongly recommended to build from source code cause the live demo is time-consuming.
